apm install \
  atom-increment \
  atom-inline-blame \
  atom-jump-block \
  atom-language-r \
  atom-notes \
  autocomplete-python \
  docblock-python \
  es6-javascript \
  es6-react-redux-snippets \
  file-icons \
  hydrogen \
  hydrogen-launcher \
  kite \
  language-atom-notes \
  language-graphql \
  language-javascript-jsx \
  language-latex \
  language-r \
  language-todo-extra-words \
  latex \
  linter-eslint \
  linter-pylint \
  markdown-preview-enhanced \
  markdown-table-editor \
  open-file \
  preview-inline \
  rainbow-csv \
  react \
  refactor \
  sort-lines \
  split-diff \
  teletype \
  todo-show \
  tree-view-copy-relative-path \
  sync-settings
