---
# TODO: First install Docker and Docker Compose:
# ansible-playbooks/docker/docker_compose_setup_playbook.yml

docker swarm init
echo "This is a file secret." > my_file_secret.txt
docker stack deploy --compose-file=docker-compose.yml secret_test
# This will create one instance of the web service, named secret_test_web.

# Use docker exec -ti [container] /bin/sh to verify that the secrets exist. 

# https://stackoverflow.com/a/42151570/3281978hj

# https://github.com/nextcloud/docker
# PostgreSQL:

#     POSTGRES_DB Name of the database using postgres.
#     POSTGRES_USER Username for the database using postgres.
#     POSTGRES_PASSWORD Password for the database user using postgres.
#     POSTGRES_HOST Hostname of the database server using postgres.


    # NEXTCLOUD_ADMIN_USER Name of the Nextcloud admin user.
    # NEXTCLOUD_ADMIN_PASSWORD Password for the Nextcloud admin user.

# RUN MULTIPLE docker-compose files, combine into one
# docker-compose -f docker-compose.db.yml \
#   -f docker-compose.api-services.yml \
#   -f docker-compose.backend.yml \
#   -f docker-compose.frontend.yml \
#   -f docker-compose.gateway.yml \
#   up -d

# OR

# docker-compose $(find docker* | sed -e 's/^/-f /') up -d